  
language: python
os: linux
dist: xenial
env:
  global:
    - HELM_URL=https://get.helm.sh
    - HELM_TGZ=helm-v3.2.4-linux-amd64.tar.gz
    - YAMLLINT_VERSION=1.15.0
    - TRAVIS_GO_VERSION=1.13.1
install:
  # Install Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzf ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
