apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec: 
  ports: 
    - 
      name: http
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector: 
    app: {{ .Release.Name }}
  type: ClusterIP
